### ISSUE TITLE
Excel file links are broken

### ISSUE THREAD

**Issue by noahemmet** [twaddington/django-olcc#12]
For example, http://www.olcc.state.or.us/pdfs/Numeric_Price_List_Next_Month.xls leads to a `Not Found On WebProd` error message.

**Comment by twaddington** [comment]
@noahemmet the CSV files listed in the README is the same data. A while back they converted to CSV but left the XLS files available. I guess they finally removed them.

I'll go ahead and update the README to remove the references to the XLS files.
