### ISSUE TITLE
Price API doesnt provide latest pricing

### ISSUE THREAD

**Issue by Soteark** [twaddington/django-olcc#15]
I could be misunderstanding how to look up a price via the API, but when I use http://www.oregonliquorprices.com/api/v1/price/ID/?format=json i.e. http://www.oregonliquorprices.com/api/v1/price/1883/?format=json

I get an old price compared to what is being displayed on the website.

**Comment by Soteark** [comment]
just want to add to this, it seems specifically with this certain ID. (1883). Guessing there are others.  The Price it shows is from 2012 even though the website shows more up to date pricing.

![image](https://user-images.githubusercontent.com/9564334/76709453-1cb91d80-66bc-11ea-89d5-f60733384b44.png)

![image](https://user-images.githubusercontent.com/9564334/76709473-38bcbf00-66bc-11ea-9222-58598e0e6e5f.png)

**Comment by twaddington** [comment]
@Soteark try this:

```
http://www.oregonliquorprices.com/api/v1/price/?format=json&product=1883
```

**Comment by twaddington** [comment]
The URL you were using before was loading the exact price entry with id "1883", not the product.

**Comment by Soteark** [comment]
Wonderful! Thank you so much, and thank you for having built this API

**Comment by twaddington** [comment]
@Soteark you're welcome! Best of luck with your project.
