### ISSUE TITLE
website doesn't work

### ISSUE THREAD

**Issue by danielb2** [twaddington/django-olcc#9]
website seems to not have any prices. Is this not being maintained anymore? it was a cool site

**Comment by twaddington** [comment]
Yeah, I noticed something broke with the last price import. I'll take a
look at it this weekend. Sometimes the file format from the OLCC changes.

Thanks for the reminder!

On Mar 14, 2015 1:54 PM, "Daniel Bretoi" <notifications@github.com> wrote:
>
> website seems to not have any prices. Is this not being maintained
anymore? it was a cool site

**Comment by twaddington** [comment]
There was a bug in the import script. I fixed the importer and am rerunning the import for the last few months. Should be fixed tonight!

**Comment by danielb2** [comment]
awesome! thanks for getting to it so quickly :)
